# Numpy basic assignment

#### AVAILABLE DATASET1

In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

list_ has type of list type and array_list has type is array which is the concept of array.

In [4]:
print(type(list_))

<class 'list'>


In [5]:
print(type(array_list))

<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [8]:
for i in list_:
    print(i, " has ",type(i))

1  has  <class 'str'>
2  has  <class 'str'>
3  has  <class 'str'>
4  has  <class 'str'>
5  has  <class 'str'>


In [12]:
print("this is the type array elements " ,array_list.dtype)

this is the type array elements  <U1


### Q3. Considering the following changes in the variable, array_list:


In [14]:
arra_list = np.array(object = list_, dtype = int)


##### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

varible list elements has string datatype and in arra_list we have changed the data type into the string . as we can see in below example.

In [15]:
for i in list_:
    print(i, " has ",type(i))

1  has  <class 'str'>
2  has  <class 'str'>
3  has  <class 'str'>
4  has  <class 'str'>
5  has  <class 'str'>


In [16]:
print("this is the type array elements " ,arra_list.dtype)

this is the type array elements  int64


#### AVAILABLE DATASET2

In [17]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:


#### (i)	 shape


#### Shape returns the shape of the data and size returns the size of data means no of elements available in the data.

In [19]:
num_array.shape

(2, 3)

##### (ii) size


In [20]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

#### [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?


#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]


In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## END